- name: install Docker
  apt:
    name: docker-ce
    update_cache: true

- name: install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: install pip
  apt:
    name: python3-pip

- name: install docker-py
  pip:
    name: docker-py
