{% if cookiecutter.registry_url -%}
# Ansible
registry_username: ""
registry_email: ""
registry_password: ""
{% endif %}
# {{ cookiecutter.app_name }}
{% for secret, environment_specific in cookiecutter.app_secrets.items() -%}
{% if environment_specific == "False" -%}
{{ cookiecutter.app_name|upper }}_{{ secret }}: ""
{% endif -%}
{% endfor %}
{% for secret, environment_specific in cookiecutter.app_secrets.items() -%}
{% if environment_specific == "True" -%}
{{ cookiecutter.app_name|upper }}_PROD_{{ secret }}: ""
{% endif -%}
{% endfor %}
{% for secret, environment_specific in cookiecutter.app_secrets.items() -%}
{% if environment_specific == "True" -%}
{{ cookiecutter.app_name|upper }}_STAGING_{{ secret }}: ""
{% endif -%}
{% endfor -%}
