{% raw -%}
- name: get existing secrets
  shell: "docker secret ls | awk '{if (NR!=1) { print $2 }}'"
  register: existing_secrets
  changed_when: false
  run_once: true

- name: add missing secrets
  shell: >
    echo "{{ vars[item] }}" | docker secret create {{ item }} -
  when: "item not in existing_secrets.stdout_lines"
  with_items: "{{ secrets }}"
  run_once: true
{% endraw -%}
