---
- name:
  remote_user: ubuntu
  become: true
  become_user: root
  hosts: all
  any_errors_fatal: true
  vars_files:
    - vars.yml
    - ../config/config.yml
    - ../config/secrets.yml
  roles:
    - common
    - docker
